origin: FoxDenHome/e621dumper

statements:
  - subjects:
      # === GitHub Actions OIDC Token Subjects ===
      # A GitHub Actions job will always have the following subjects
      # The original OIDC token 'sub' claim e.g. repo:${origin}:ref:refs/heads/main or repo:${origin}:environment:production
      # repo:${origin}:ref:<ref> e.g. repo:${origin}:ref:refs/heads/main
      # repo:${origin}:environment:<environment> e.g. repo:${origin}:environment:production
      # repo:${origin}:workflow_ref:<workflow_ref> e.g. repo:${origin}:workflow_ref:${origin}/.github/workflows/build.yml@refs/heads/main
      # repo:${origin}:job_workflow_ref:<job_workflow_ref> e.g. repo:${origin}:job_workflow_ref:${origin}/.github/workflows/build.yml@refs/heads/main

      # === Subject Pattern Variables ===
      # ${origin} - the origin repository name e.g. qoomon/sandbox

      - repo:${origin}
    permissions:
      contents: write
