name: Fixup

on:
  push: {}

concurrency:
    group: fixup-${{ github.ref }}
    cancel-in-progress: true

jobs:
  fixup_npm_deps_hash:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fix flake.nix npmDepsHash
        run: |
          HASH="$(nix run nixpkgs#prefetch-npm-deps package-lock.json)"
          echo "New hash: $HASH"
          sed "s~npmDepsHash = \".*\"~npmDepsHash = \"$HASH\"~g" -i flake.nix
      - uses: stefanzweifel/git-auto-commit-action@v6
        id: auto_commit
        with:
          commit_message: "fixup: update npmDepsHash"
          branch: ${{ github.ref_name }}

  lint_and_build:
    permissions:
        contents: read
        checks: write
    uses: ./.github/workflows/lint_build.yml
    with:
      sha: ${{ needs.fixup_npm_deps_hash.result.auto_commit.outputs.commit_hash }}
    needs: [fixup_npm_deps_hash]
    secrets: inherit
