name: Format

on:
  push: {}

jobs:
  fixup-npm-deps-hash:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          HASH="$(nix run nixpkgs#prefetch-npm-deps package-lock.json)"
          sed "s/npmDepsHash = \".*\"/npmDepsHash = \"$HASH\"/g" -i flake.nix
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          branch: ${{ github.ref_name }}
