name: Nix

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix build .
